BUILDER_BASE_IMAGE=quay.io/aipcc/base-images/cuda-12.9-el9.6:3.5.0-1786555851
BUILDER_DNF_COMMAND=dnf
RUNTIME_BASE_IMAGE=quay.io/aipcc/base-images/cuda-12.9-el9.6:3.5.0-1786555851
RUNTIME_DNF_COMMAND=dnf
