BUILDER_BASE_IMAGE=quay.io/aipcc/base-images/cuda-12.9-el9.6:3.4.2-1782914793
BUILDER_DNF_COMMAND=dnf
RUNTIME_BASE_IMAGE=quay.io/aipcc/base-images/cuda-12.9-el9.6:3.4.2-1782914793
RUNTIME_DNF_COMMAND=dnf
