apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "true"
  name: rag-content-e2e-tests
  namespace: lightspeed-core-tenant
spec:
  application: rag
  contexts:
  - description: execute the integration test in all cases - this would be the default
      state
    name: application
  resolverRef:
    params:
    - name: url
      value: https://github.com/syedriko/lightspeed-core-rag-content.git
    - name: revision
      value: syedriko-lcore-2435
    - name: pathInRepo
      value: .tekton/integration-tests/pipeline/rag-content-integration-test.yaml
    resolver: git
    resourceKind: pipeline
