[common]
python_version = "3.12"
platforms = ["x86_64", "aarch64"]
bootstrap_packages = []
force_sdist_packages = ["setuptools", "packaging", "pluggy"]

[profiles.cpu]
rhoai_index_url = "https://packages.redhat.com/api/pypi/public-rhai/rhoai/3.4/cpu-ubi9/simple/"
output_suffix = ""
tekton_files = [
    ".tekton/rag-tool-pull-request.yaml",
    ".tekton/rag-tool-push.yaml",
    ".tekton/rag-content-cpu-0-5-pull-request.yaml",
    ".tekton/rag-content-cpu-0-5-push.yaml",
]
