#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["packaging>=24.1"]
# ///
r"""Generate requirements.overrides.txt for Konflux dual-index compiles.

Runs `uv pip compile` with PyPI + RHOAI and `--emit-index-annotation`, using the same
``--universal`` and ``--python-version`` as ``scripts/konflux_requirements.sh`` so index
annotations match Konflux.

The annotation compile is run **without** ``--override`` by default so PyPI-sourced packages
(e.g. transitive ``nltk``, ``accelerate``) appear in ``parse_pypi_sourced_pins``. Seeding from the
existing ``-o`` file would hide those lines and under-generate pins. Use ``--seed-override`` only
for experiments. Pins for packages declared
with extras in ``[tool.uv] constraint-dependencies`` are written as ``name[extras]==…``.
For direct ``[project]`` dependencies, a candidate RHOAI pin is **skipped** (with a warning) if
its version does not satisfy that dependency line—whether written as ``==``, a range, or any PEP 440
specifier (``packaging`` ``Specifier.contains``).
Candidate RHOAI pins are then **filtered for solvability**: the script tries the full set once,
then forward-adds in order (exact RHOAI hits first, then name) so ``uv pip compile`` with dual
indexes and ``--override`` still succeeds—dropping pins that would jointly contradict
``pyproject.toml``.
After writing, runs a final dual-index compile with ``--override`` and exits non-zero if the
project does not resolve.

Also adds RHOAI pins for direct ``[project.dependencies]`` that were **not** PyPI-sourced in the
annotation compile (so they are missing from the PyPI→RHOAI pass). That keeps packages such as
``faiss-cpu`` on RHOAI wheels when other overrides would otherwise flip the graph to PyPI.

  uv run --script scripts/generate_requirements_overrides.py -o requirements.overrides.txt

Use `--compiled-input` to pass an existing annotated file instead of running uv.
"""

from __future__ import annotations

import argparse
import html.parser
import os
import re
import subprocess
import sys
import tempfile
import tomllib
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urljoin, urlparse

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name, parse_sdist_filename, parse_wheel_filename
from packaging.version import InvalidVersion, Version

DEFAULT_RHOAI = "https://console.redhat.com/api/pypi/public-rhai/rhoai/3.3/cpu-ubi9/simple/"
DEFAULT_PYPI = "https://pypi.org/simple/"
# Must match konflux_requirements.sh: same `uv pip compile` --python-version.
DEFAULT_PYTHON_VERSION = "3.12"

PYPI_SIMPLE_MARKER = "pypi.org/simple"

HEADER = (
    "# Selective pins for `uv pip compile --override` with dual indexes and\n"
    "# `--index-strategy unsafe-first-match` "
    "(same as konflux: RHOAI index before PyPI for each package).\n"
    "# Generated by scripts/generate_requirements_overrides.py\n"
    f"# RHOAI: {DEFAULT_RHOAI}\n"
)

USER_AGENT = (
    "ols-generate-requirements-overrides/1.0 "
    "(compatible; +https://github.com/openshift/lightspeed-service)"
)


@dataclass(frozen=True)
class OverrideCandidate:
    """One proposed override line and metadata for solvability ordering."""

    canonical_name: str
    line: str
    exact_rhoai_match: bool


@dataclass
class LinkParser(html.parser.HTMLParser):
    hrefs: list[str]

    def __init__(self) -> None:
        super().__init__()
        self.hrefs = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag != "a":
            return
        for name, value in attrs:
            if name == "href" and value:
                self.hrefs.append(value)
                return


def _basename_from_href(href: str) -> str | None:
    path = urlparse(href).path
    name = path.rsplit("/", 1)[-1]
    if not name or name in (".", ".."):
        return None
    return name.split("#", 1)[0]


def _version_from_artifact_filename(filename: str) -> Version | None:
    lowered = filename.lower()
    try:
        if lowered.endswith(".whl"):
            _n, ver, _b, _t = parse_wheel_filename(filename)
            return ver
        if lowered.endswith(".tar.gz") or lowered.endswith(".zip"):
            _n, ver = parse_sdist_filename(filename)
            return ver
    except (ValueError, InvalidVersion):
        return None
    return None


def fetch_versions_for_project(
    index_url: str,
    project_name: str,
    opener: urllib.request.OpenerDirector,
) -> list[Version]:
    normalized = canonicalize_name(project_name)
    base = index_url if index_url.endswith("/") else index_url + "/"
    url = urljoin(base, f"{normalized}/")
    req = urllib.request.Request(url, method="GET")
    try:
        with opener.open(req, timeout=120) as resp:
            body = resp.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return []
        raise
    parser = LinkParser()
    parser.feed(body)
    versions: set[Version] = set()
    for href in parser.hrefs:
        base_name = _basename_from_href(href)
        if not base_name:
            continue
        ver = _version_from_artifact_filename(base_name)
        if ver is not None:
            versions.add(ver)
    return sorted(versions)


def _is_pypi_simple_index(url: str) -> bool:
    u = url.rstrip("/").lower()
    return PYPI_SIMPLE_MARKER in u


def _normalize_rhoai_base(url: str) -> str:
    return url if url.endswith("/") else url + "/"


def _pin_version_from_requirement(req: Requirement) -> Version | None:
    for spec in req.specifier:
        if spec.operator in ("==", "==="):
            try:
                return Version(spec.version)
            except InvalidVersion:
                return None
    return None


def _uv_sources_canonical_keys(pyproject: Path) -> frozenset[str]:
    """Canonical names of packages with ``[tool.uv.sources]`` (those indexes, not RHOAI pins)."""
    data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    sources = ((data.get("tool") or {}).get("uv") or {}).get("sources") or {}
    if not isinstance(sources, dict):
        return frozenset()
    out: set[str] = set()
    for pkg_name in sources:
        if isinstance(pkg_name, str):
            out.add(canonicalize_name(pkg_name))
    return frozenset(out)


def _constraint_dependency_extras(pyproject: Path) -> dict[str, frozenset[str]]:
    """Map canonical package name -> extras declared in [tool.uv] constraint-dependencies."""
    data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    tool_uv = (data.get("tool") or {}).get("uv") or {}
    raw = tool_uv.get("constraint-dependencies")
    if not raw or not isinstance(raw, list):
        return {}
    merged: dict[str, set[str]] = {}
    for line in raw:
        if not isinstance(line, str) or not line.strip():
            continue
        try:
            req = Requirement(line.strip())
        except ValueError:
            continue
        key = canonicalize_name(req.name)
        if not req.extras:
            continue
        merged.setdefault(key, set()).update(req.extras)
    return {k: frozenset(v) for k, v in merged.items()}


def _project_dependency_requirements(pyproject: Path) -> dict[str, Requirement]:
    """Map canonical package name -> ``Requirement`` for each ``[project]`` dependency line."""
    data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    deps = (data.get("project") or {}).get("dependencies") or []
    out: dict[str, Requirement] = {}
    for line in deps:
        if not isinstance(line, str) or not line.strip():
            continue
        try:
            req = Requirement(line.strip())
        except ValueError:
            continue
        out[canonicalize_name(req.name)] = req
    return out


def _project_dep_applies(req: Requirement) -> bool:
    """Return whether this dependency applies (marker), or has no marker."""
    if req.marker is None:
        return True
    return req.marker.evaluate()


def _chosen_satisfies_project_dep(chosen: Version, req: Requirement) -> bool:
    """Return whether ``chosen`` matches ``req``'s specifier, or ``req`` is inactive (marker)."""
    if not _project_dep_applies(req):
        return True
    return req.specifier.contains(chosen, prereleases=True)


def _best_rhoai_version_for_direct_requirement(
    avail: list[Version],
    req: Requirement,
) -> Version | None:
    """Newest RHOAI version that satisfies the direct dependency line, if any."""
    if not _project_dep_applies(req):
        return None
    sat = [v for v in avail if req.specifier.contains(v, prereleases=True)]
    if not sat:
        return None
    return max(sat)


def _format_override_pin(
    name: str,
    chosen: Version,
    extras_by_pkg: dict[str, frozenset[str]],
) -> str:
    extras = extras_by_pkg.get(canonicalize_name(name))
    if extras:
        extra_str = ",".join(sorted(extras))
        return f"{name}[{extra_str}]=={chosen}"
    return f"{name}=={chosen}"


def parse_pypi_sourced_pins(compiled_text: str, rhoai_index_url: str) -> list[tuple[str, Version]]:
    """Return (name, resolved_version) for packages whose # from line is PyPI simple."""
    rhoai_norm = _normalize_rhoai_base(rhoai_index_url).rstrip("/").lower()
    lines = compiled_text.splitlines()
    out: list[tuple[str, Version]] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip() or line.lstrip().startswith("#"):
            i += 1
            continue
        if line[0] in " \t" or "==" not in line:
            i += 1
            continue
        pkg_line = line.strip()
        i += 1
        index_url: str | None = None
        while i < len(lines):
            cont = lines[i]
            if cont and cont[0] not in " \t" and not cont.lstrip().startswith("#") and "==" in cont:
                break
            if "# from " in cont or cont.strip().startswith("# from"):
                m = re.search(r"#\s*from\s+(\S+)", cont)
                if m:
                    index_url = m.group(1).strip().rstrip("/")
            i += 1
        if index_url is None:
            continue
        idx_lower = index_url.lower()
        if rhoai_norm and idx_lower.startswith(rhoai_norm):
            continue
        if not _is_pypi_simple_index(index_url):
            continue
        try:
            req = Requirement(pkg_line.split(";", 1)[0].strip())
        except (ValueError, InvalidVersion):
            continue
        ver = _pin_version_from_requirement(req)
        if ver is None:
            continue
        out.append((req.name, ver))
    return out


def run_uv_compile(
    pyproject: Path,
    rhoai_index: str,
    pypi_index: str,
    python_version: str,
    extras: list[str],
    extra_uv_args: list[str],
    seed_override: Path | None,
) -> str:
    out = Path(tempfile.mkstemp(suffix=".txt", prefix="uv-annotate-")[1])
    cmd = [
        "uv",
        "pip",
        "compile",
        str(pyproject),
        "-o",
        str(out),
        "--index-strategy",
        "unsafe-first-match",
        "--python-version",
        python_version,
        "--universal",
        "--refresh",
        "--index",
        _normalize_rhoai_base(rhoai_index),
        "--default-index",
        _normalize_rhoai_base(pypi_index),
        "--emit-index-annotation",
        "--no-sources",
    ]
    if seed_override is not None and seed_override.is_file():
        cmd.extend(["--override", str(seed_override)])
    for e in extras:
        cmd.extend(["--extra", e])
    cmd.extend(extra_uv_args)
    proc = subprocess.run(cmd, capture_output=True, text=True)
    try:
        if proc.returncode != 0:
            sys.stderr.write(proc.stderr or proc.stdout or "")
            raise SystemExit(proc.returncode or 1)
        return out.read_text(encoding="utf-8")
    finally:
        out.unlink(missing_ok=True)


def _dual_index_compile_with_override(
    pyproject: Path,
    rhoai_index: str,
    pypi_index: str,
    python_version: str,
    override_path: Path,
    extras: list[str],
    extra_uv_args: list[str],
) -> subprocess.CompletedProcess[str]:
    """Run ``uv pip compile`` (dual indexes) with ``--override``; return completed process."""
    out = Path(tempfile.mkstemp(suffix=".txt", prefix="uv-verify-")[1])
    cmd = [
        "uv",
        "pip",
        "compile",
        str(pyproject),
        "-o",
        str(out),
        "--override",
        str(override_path),
        "--index-strategy",
        "unsafe-first-match",
        "--python-version",
        python_version,
        "--universal",
        "--index",
        _normalize_rhoai_base(rhoai_index),
        "--default-index",
        _normalize_rhoai_base(pypi_index),
        "--no-sources",
    ]
    for e in extras:
        cmd.extend(["--extra", e])
    cmd.extend(extra_uv_args)
    proc = subprocess.run(cmd, capture_output=True, text=True)
    out.unlink(missing_ok=True)
    return proc


def verify_override_resolution(
    pyproject: Path,
    rhoai_index: str,
    pypi_index: str,
    python_version: str,
    override_path: Path,
    extras: list[str],
    extra_uv_args: list[str],
) -> None:
    """Fail if pyproject cannot be resolved with the generated override file."""
    proc = _dual_index_compile_with_override(
        pyproject,
        rhoai_index,
        pypi_index,
        python_version,
        override_path,
        extras,
        extra_uv_args,
    )
    if proc.returncode != 0:
        sys.stderr.write(
            "Override pins do not resolve with the project (dual-index compile failed).\n"
            "Adjust [project] dependencies and regenerate.\n\n",
        )
        sys.stderr.write(proc.stderr or proc.stdout or "")
        raise SystemExit(proc.returncode or 1)


def _override_body_solves(
    pin_lines: list[str],
    pyproject: Path,
    rhoai_index: str,
    pypi_index: str,
    python_version: str,
    extras: list[str],
    extra_uv_args: list[str],
    include_header: bool,
) -> bool:
    """Return whether ``uv pip compile`` succeeds with this override body."""
    body = "\n".join(pin_lines) + "\n"
    if include_header:
        body = HEADER + "\n" + body
    fd, path = tempfile.mkstemp(suffix=".txt", prefix="uv-greedy-")
    tmp = Path(path)
    try:
        os.close(fd)
        tmp.write_text(body, encoding="utf-8")
        proc = _dual_index_compile_with_override(
            pyproject,
            rhoai_index,
            pypi_index,
            python_version,
            tmp,
            extras,
            extra_uv_args,
        )
    finally:
        tmp.unlink(missing_ok=True)
    return proc.returncode == 0


def _maximize_solvable_rhoai_pins(
    candidates: list[OverrideCandidate],
    pyproject: Path,
    rhoai_index: str,
    pypi_index: str,
    python_version: str,
    extras: list[str],
    extra_uv_args: list[str],
    include_header: bool,
) -> tuple[list[str], list[str]]:
    """Keep as many RHOAI pins as possible while dual-index ``uv pip compile`` still succeeds.

    Tries the full candidate set first (one compile), then forward-greedy add in a stable order:
    exact RHOAI matches first, then alphabetical. This keeps runtime ~O(n) compiles in the common
    case instead of trying every permutation ordering.
    """
    if not candidates:
        return [], []

    all_lines = [c.line for c in candidates]
    if _override_body_solves(
        all_lines,
        pyproject,
        rhoai_index,
        pypi_index,
        python_version,
        extras,
        extra_uv_args,
        include_header,
    ):
        return all_lines, []

    order = sorted(
        candidates,
        key=lambda c: (not c.exact_rhoai_match, c.canonical_name),
    )
    acc: list[str] = []
    for c in order:
        trial = [*acc, c.line]
        if _override_body_solves(
            trial,
            pyproject,
            rhoai_index,
            pypi_index,
            python_version,
            extras,
            extra_uv_args,
            include_header,
        ):
            acc.append(c.line)

    best_set = set(acc)
    notes: list[str] = []
    for c in candidates:
        if c.line not in best_set:
            notes.append(
                f"{c.canonical_name}: omitted RHOAI pin (would break dual-index resolution with "
                f"other selected pins / pyproject.toml)",
            )
    return acc, notes


def build_opener() -> urllib.request.OpenerDirector:
    class UserAgentHandler(urllib.request.BaseHandler):
        def http_request(self, req: urllib.request.Request) -> urllib.request.Request:
            if req.get_header("User-agent") is None:
                req.add_header("User-Agent", USER_AGENT)
            return req

        https_request = http_request

    return urllib.request.build_opener(UserAgentHandler())


def main() -> None:
    p = argparse.ArgumentParser(
        description="Generate selective requirements.overrides.txt from annotated uv compile.",
    )
    p.add_argument("--pyproject", type=Path, default=Path("pyproject.toml"))
    p.add_argument(
        "--compiled-input",
        type=Path,
        help="Annotated compile output (skip running uv if set)",
    )
    p.add_argument("--rhoai-index", default=DEFAULT_RHOAI)
    p.add_argument("--pypi-index", default=DEFAULT_PYPI)
    p.add_argument("--python-version", default=DEFAULT_PYTHON_VERSION)
    p.add_argument("--extra", action="append", default=[], metavar="NAME")
    p.add_argument("-o", "--output", type=Path, default=Path("requirements.overrides.txt"))
    p.add_argument("--no-header-comment", action="store_true")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument(
        "--seed-override",
        action="store_true",
        help=(
            "Pass existing -o as --override for the annotation compile "
            "(hides PyPI-sourced pins; default is clean compile for discovery)"
        ),
    )
    p.add_argument(
        "uv_extra",
        nargs="*",
        help="Extra args forwarded to uv pip compile when generating input",
    )
    args = p.parse_args()

    if args.compiled_input:
        text = args.compiled_input.read_text(encoding="utf-8")
    else:
        if not args.pyproject.is_file():
            raise SystemExit(f"Not found: {args.pyproject}")
        seed_override: Path | None = None
        if args.seed_override and args.output.is_file():
            seed_override = args.output
        text = run_uv_compile(
            args.pyproject,
            args.rhoai_index,
            args.pypi_index,
            args.python_version,
            args.extra,
            args.uv_extra,
            seed_override,
        )

    pypi_pins = parse_pypi_sourced_pins(text, args.rhoai_index)

    opener = build_opener()
    extras_by_pkg = _constraint_dependency_extras(args.pyproject)
    project_reqs = _project_dependency_requirements(args.pyproject)
    candidates: list[OverrideCandidate] = []
    warnings: list[str] = []

    for name, want in sorted(pypi_pins, key=lambda t: canonicalize_name(t[0])):
        key = canonicalize_name(name)
        avail = fetch_versions_for_project(args.rhoai_index, name, opener)
        if not avail:
            warnings.append(f"{name}: not on RHOAI index, skip")
            continue
        if want in avail:
            chosen = want
        else:
            # RHOAI often ships rebuilds like 3.9.2-2 while PyPI has 3.9.2; then v <= want is empty.
            # Prefer the closest RHOAI version at or above PyPI's resolution, then best below.
            not_below = [v for v in avail if v >= want]
            not_newer = [v for v in avail if v <= want]
            if not_below:
                chosen = min(not_below)
                if chosen != want:
                    warnings.append(
                        f"{name}: PyPI had {want}, RHOAI closest ≥ that is {chosen} "
                        f"(e.g. rebuild; pin this so dual-index uses RHOAI)",
                    )
            elif not_newer:
                chosen = max(not_newer)
                warnings.append(
                    f"{name}: PyPI had {want}, RHOAI best <= that is {chosen} (no exact match)",
                )
            else:
                warnings.append(
                    f"{name}: PyPI had {want}, RHOAI has no overlapping version; skip",
                )
                continue
        proj_req = project_reqs.get(key)
        if proj_req is not None and not _chosen_satisfies_project_dep(chosen, proj_req):
            warnings.append(
                f"{name}: RHOAI pin would be {chosen}, which does not satisfy pyproject.toml "
                f"({proj_req})",
            )
            continue
        pin_line = _format_override_pin(name, chosen, extras_by_pkg)
        candidates.append(
            OverrideCandidate(
                canonical_name=key,
                line=pin_line,
                exact_rhoai_match=(chosen == want),
            ),
        )

    # Direct [project.dependencies] RHOAI pins only when the annotation compile did *not* mark the
    # package as PyPI-sourced (so it is absent from ``pypi_pins``). Those packages already have
    # RHOAI (or another non-PyPI index) in the first resolve; without an explicit override, adding
    # other pins (e.g. nltk) can flip them to PyPI on the next compile. Do not duplicate packages
    # from ``pypi_pins``, and do not pin ``[tool.uv.sources]`` packages (e.g. torch/torchvision).
    pypi_sourced_keys = {canonicalize_name(n) for n, _ in pypi_pins}
    uv_sources_keys = _uv_sources_canonical_keys(args.pyproject)
    seen = {c.canonical_name for c in candidates}
    for pkg_key, proj_req in sorted(project_reqs.items(), key=lambda t: str(t[0])):
        if str(pkg_key) in seen:
            continue
        if pkg_key in uv_sources_keys:
            continue
        if pkg_key in pypi_sourced_keys:
            continue
        avail = fetch_versions_for_project(args.rhoai_index, proj_req.name, opener)
        rhoai_pick = _best_rhoai_version_for_direct_requirement(avail, proj_req)
        if rhoai_pick is None:
            continue
        pin_line = _format_override_pin(proj_req.name, rhoai_pick, extras_by_pkg)
        warnings.append(
            f"{proj_req.name}: RHOAI-only in annotation compile → pin {rhoai_pick} "
            f"(prevents flipping to PyPI when other overrides apply)",
        )
        candidates.append(
            OverrideCandidate(
                canonical_name=str(pkg_key),
                line=pin_line,
                exact_rhoai_match=True,
            ),
        )

    if not pypi_pins and not candidates:
        raise SystemExit(
            "No PyPI-sourced pins in annotated input and no RHOAI pins from "
            "[project.dependencies]. Use an uv compile output with --emit-index-annotation.",
        )
    if not candidates:
        raise SystemExit(
            "No RHOAI override candidates (check RHOAI index and pyproject.toml).",
        )

    for w in warnings:
        print(w, file=sys.stderr)

    lines_out, omission_notes = _maximize_solvable_rhoai_pins(
        candidates,
        args.pyproject,
        args.rhoai_index,
        args.pypi_index,
        args.python_version,
        args.extra,
        args.uv_extra,
        not args.no_header_comment,
    )
    for note in omission_notes:
        print(note, file=sys.stderr)

    body = "\n".join(lines_out) + "\n"
    if not args.no_header_comment:
        body = HEADER + "\n" + body

    if args.dry_run:
        sys.stdout.write(body)
        return

    args.output.write_text(body, encoding="utf-8")
    if not args.compiled_input:
        verify_override_resolution(
            args.pyproject,
            args.rhoai_index,
            args.pypi_index,
            args.python_version,
            args.output,
            args.extra,
            args.uv_extra,
        )

    omitted = len(candidates) - len(lines_out)
    print(
        f"Wrote {args.output} ({len(lines_out)} pins from {len(candidates)} RHOAI candidates, "
        f"{len(pypi_pins)} PyPI-sourced in annotation; {omitted} omitted as unsolvable "
        "with pyproject)",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
