#!/bin/bash

# Script to split requirements by index source.
#
# Policy (CPU hermetic):
#   1) RHOAI — If uv resolves a package from the RHOAI index, keep it on requirements.wheel.txt (RHOAI wheels).
#   2) PyPI — Prefer hashed sdists (requirements.hashes.source.txt / build from source at image build).
#   3) PyPI wheels — Only for packages listed in PYPI_WHEEL_LAST_RESORT (cannot use sdist in Hermeto/pip
#      reliably: Rust/C++ bootstrap, no sdist on PyPI, psycopg2-binary vs sdist, etc.). Add names here when
#      prefetch or build fails, not preemptively for every transitive.
#
# stop on error and print commands
set -ex

RAW_REQ_FILE="requirements.no_hashes.txt"
SOURCE_FILE="requirements.source.txt"
WHEEL_FILE="requirements.wheel.cuda.txt"
WHEEL_FILE_PYPI="requirements.wheel.pypi.cuda.txt"
SOURCE_HASH_FILE="requirements.hashes.source.cuda.txt"
WHEEL_HASH_FILE="requirements.hashes.wheel.cuda.txt"
WHEEL_HASH_FILE_PYPI="requirements.hashes.wheel.pypi.cuda.txt"
BUILD_FILE="requirements-build.cuda.txt"
RHOAI_INDEX_URL="https://packages.redhat.com/api/pypi/public-rhai/rhoai/3.4/cuda12.9-ubi9/simple/"

# Prefetch as wheels for image pip/bootstrap (not project deps).
EXTRA_WHEELS="uv-build,uv,pip,maturin"
# PyPI: wheel is last resort — expand this comma list only when hashed sdist path fails (Hermeto or Containerfile build).
# hf-xet / jiter: Rust sdists fragile under Hermeto; psycopg2-binary: avoid pg_config sdist path.
# tokenizers: PyPI publishes manylinux wheels; sdist requires Rust/cargo at image build — use wheel only.
# torch/torchvision/triton: if uv ever resolves these from PyPI, there is no practical sdist — wheels only.
PYPI_WHEEL_LAST_RESORT="hf-xet,psycopg2-binary,jiter,docling-parse,tokenizers,torch,torchvision,triton,opencv-python,rapidocr,sqlite-vec"

# Generate requirements list from pyproject.toml from both indexes
uv pip compile pyproject.toml -o "$RAW_REQ_FILE" \
		--python-platform x86_64-unknown-linux-gnu \
		--python-version 3.12 \
		--refresh \
		--index $RHOAI_INDEX_URL \
		--default-index https://pypi.org/simple/ \
		--index-strategy unsafe-best-match \
		--emit-index-annotation \
		--no-sources \
		--override requirements.overrides.cuda.txt

# Initialize output files
echo "# Packages from pypi.org" > "$SOURCE_FILE"
echo "# This file was autogenerated by konflux_requirements.sh" >> "$SOURCE_FILE"
echo "# Packages from packages.redhat.com" > "$WHEEL_FILE"
echo "# This file was autogenerated by konflux_requirements.sh" >> "$WHEEL_FILE"
echo "--index-url $RHOAI_INDEX_URL" >> "$WHEEL_FILE"
echo "# Packages from pypi.org to be fetched as wheels" > "$WHEEL_FILE_PYPI"
echo "# This file was autogenerated by konflux_requirements.sh" >> "$WHEEL_FILE_PYPI"

current_package=""

while IFS= read -r line || [[ -n "$line" ]]; do
    # Check if this is a package line (starts with a letter/digit, not whitespace or #)
    if [[ "$line" =~ ^[a-zA-Z0-9] ]]; then
        current_package="$line"
    # Check if this is a "# from" annotation line
    elif [[ "$line" =~ ^[[:space:]]*#[[:space:]]*from[[:space:]]+(.*) ]]; then
        index_url="${BASH_REMATCH[1]}"

        if [[ -n "$current_package" ]]; then
            if [[ "$index_url" == "https://pypi.org/simple/" ]]; then
                # Extract package name (without version) for comparison
                package_name=$(echo "$current_package" | sed 's/[=<>!].*//')
                if echo ",${PYPI_WHEEL_LAST_RESORT}," | grep -qF ",${package_name},"; then
                    echo "$current_package" >> "$WHEEL_FILE_PYPI"
                else
                    echo "$current_package" >> "$SOURCE_FILE"
                fi
            elif [[ "$index_url" == "$RHOAI_INDEX_URL" ]]; then
                echo "$current_package" >> "$WHEEL_FILE"
            fi
            current_package=""
        fi
    fi
done < "$RAW_REQ_FILE"

# Binary prefetch: RHOAI wheel names + PyPI last-resort wheels + bootstrap tools (Hermeto fetches wheels for these).
wheel_packages=$(grep -vE '^#|^--' "$WHEEL_FILE" | sed '/^$/d' | sed 's/==.*//' | tr '\n' ',' | sed 's/,$//')
pypi_wheel_packages=$(grep -vE '^#|^--' "$WHEEL_FILE_PYPI" | sed '/^$/d' | sed 's/==.*//' | tr '\n' ',' | sed 's/,$//')
wheel_packages="$wheel_packages,$EXTRA_WHEELS,$pypi_wheel_packages"
wheel_packages=$(printf '%s' "$wheel_packages" | tr ',' '\n' | awk 'NF && !seen[$0]++' | paste -sd, -)
for _tekton_prefetch in \
	.tekton/rag-tool-cuda-pull-request.yaml \
	.tekton/rag-tool-cuda-push.yaml ; do
	sed -i 's/"packages": "[^"]*"/"packages": "'"$wheel_packages"'"/' "$_tekton_prefetch"
done

echo "Packages from pypi.org written to: $SOURCE_FILE ($(wc -l < "$SOURCE_FILE") packages)"
echo "Packages from packages.redhat.com written to: $WHEEL_FILE ($(wc -l < "$WHEEL_FILE") packages)"


# Use stdout redirection instead of -o flag to work around uv bug where -o reuses stale hashes from existing output file
# Do NOT add PyPI as --extra-index-url here: uv would record PyPI wheel digests while Hermeto prefetches RHOAI rebuilds
# (*-N-*.whl), causing "checksum mismatch" / "No wheels found" for every such package.
# RHOAI simple must list wheels for --universal; if compile fails or is incomplete, add a direct pulp pin below.
# Hermeto/cachi2 prefetch does not support --extra-index-url in requirement files.
# RHOAI wheel pins (full set — not moved to PyPI for hash convenience).
if grep -qE '^[a-zA-Z0-9][a-zA-Z0-9_.-]*==' "$WHEEL_FILE"; then
	uv pip compile "$WHEEL_FILE" --refresh --generate-hashes \
		--index-url $RHOAI_INDEX_URL --index-strategy unsafe-best-match \
		--python-version 3.12 --emit-index-url --no-deps --no-annotate --universal > "$WHEEL_HASH_FILE"
else
	printf '%s\n' "# No RHOAI-only wheel pins; all other wheels use PyPI hashes in requirements.hashes.wheel.pypi.txt." > "$WHEEL_HASH_FILE"
	printf '%s\n' "--index-url $RHOAI_INDEX_URL" >> "$WHEEL_HASH_FILE"
fi
sed -i '/^--extra-index-url/d' "$WHEEL_HASH_FILE"
if grep -qE '^[a-zA-Z0-9][a-zA-Z0-9_.-]*==' "$WHEEL_FILE_PYPI"; then
	uv pip compile "$WHEEL_FILE_PYPI" --refresh --generate-hashes --python-version 3.12 --emit-index-url --no-deps --no-annotate > "$WHEEL_HASH_FILE_PYPI"
else
	printf '%s\n' "# No PyPI wheel-only (last-resort) pins." > "$WHEEL_HASH_FILE_PYPI"
fi
# Hermeto fetches wheels per file index: RHOAI for .wheel.txt, PyPI for .pypi.txt. If a package
# appears in both, pip must see PyPI hashes (prefetched wheel). Drop the RHOAI copy (same as CUDA script).
awk 'FNR==NR { if (/^[a-zA-Z0-9].*(==| @ )/) { match($0, /^[a-zA-Z0-9][a-zA-Z0-9_.-]*/); p[substr($0,RSTART,RLENGTH)]=1 }; next }
     /^#/ { print; next }
     /^--index-url/ { print; next }
     /^[a-zA-Z0-9].*(==| @ )/ { match($0, /^[a-zA-Z0-9][a-zA-Z0-9_.-]*/); name=substr($0,RSTART,RLENGTH); skip=(name in p); if (!skip) print; next }
     { if (!skip) print }' "$WHEEL_HASH_FILE_PYPI" "$WHEEL_HASH_FILE" > "${WHEEL_HASH_FILE}.tmp" && mv "${WHEEL_HASH_FILE}.tmp" "$WHEEL_HASH_FILE"
# Same filter as pybuild-deps: never emit hashed source lines for CUDA stack / wheel-only pins into the
# CPU hermetic source file — Hermeto cannot satisfy them (e.g. nvidia-* has no usable sdist for fetch-deps).
grep -v -E '^(torch|torchvision|triton|faiss-cpu|nvidia-[a-zA-Z0-9_-]+)==' "$SOURCE_FILE" > "${SOURCE_FILE}.hashcompile"
uv pip compile "${SOURCE_FILE}.hashcompile" --refresh --generate-hashes --python-version 3.12 --emit-index-url --no-deps --no-annotate > "$SOURCE_HASH_FILE"
rm -f "${SOURCE_FILE}.hashcompile"
# pybuild-deps cannot fetch nvidia-* / torch stack sdists from PyPI; those are wheel-only in this image.
grep -v -E '^(torch|torchvision|triton|faiss-cpu|nvidia-[a-zA-Z0-9_-]+)==' "$SOURCE_FILE" > "${SOURCE_FILE}.build"
uv run pybuild-deps compile --output-file="$BUILD_FILE" "${SOURCE_FILE}.build"
rm -f "${SOURCE_FILE}.build"

# pin maturin to the version available in the Red Hat registry
sed -i 's/maturin==[0-9.]*/maturin==1.10.2/' "$BUILD_FILE"

# remove intermediate files
rm "$RAW_REQ_FILE" "$WHEEL_FILE" "$WHEEL_FILE_PYPI" "$SOURCE_FILE"

echo "Done!"
echo "Packages from pypi.org written to: $SOURCE_HASH_FILE ($( grep -Eo '==[0-9.]+' "$SOURCE_HASH_FILE" | wc -l) packages)"
echo "Packages from packages.redhat.com written to: $WHEEL_HASH_FILE ($(grep -Eo '==[0-9.]+' "$WHEEL_HASH_FILE" | wc -l) packages)"
echo "Packages from pypi.org (wheels) written to: $WHEEL_HASH_FILE_PYPI ($(grep -Eo '==[0-9.]+' "$WHEEL_HASH_FILE_PYPI" | wc -l) packages)"
echo "Build dependencies written to: $BUILD_FILE ($(grep -Eo '==[0-9.]+' "$BUILD_FILE" | wc -l) packages)"
echo "Remember to commit $SOURCE_HASH_FILE, $WHEEL_HASH_FILE, $WHEEL_HASH_FILE_PYPI, $BUILD_FILE, Containerfile, pipeline configurations and push the changes"
