name: Build CPU image, release/0.7 branch push quay.io

on:
  push:
    branches: ["release/0.7"]
  pull_request:
    branches: ["release/0.7"]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-dev:
    uses: ./.github/workflows/build_and_push_container.yaml
    with:
      image_name: rag-content-cpu
      container_file: Containerfile
    secrets:
      QUAY_REGISTRY_USERNAME: ${{ secrets.QUAY_REGISTRY_USERNAME }}
      QUAY_REGISTRY_PASSWORD: ${{ secrets.QUAY_REGISTRY_PASSWORD }}
